---
name: Developer image
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'Dockerfile'
      - '**.sh'
      - 'go.mod'
      - 'go.sum'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker - GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
          tags: type=raw,value=dev
          flavor: latest=true

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
